sudo: required
services:
  - docker

before_install:
  - docker build -t ashujoshi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ashujoshi/react-test npm test -- --coverage

after_success:
  - docker build -t ashujoshi/multi-client ./client
  - docker build -t ashujoshi/multi-nginx ./nginx
  - docker build -t ashujoshi/multi-server ./server
  - docker build -t ashujoshi/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ashujoshi/multi-client
  - docker push ashujoshi/multi-worker
  - docker push ashujoshi/multi-server
  - docker push ashujoshi/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-389714728067
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY